{% set name = "microsoft-kiota-abstractions" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_abstractions-{{ version }}.tar.gz
  sha256: fb3db244b50ab99c8cd4aa40ce40b749e3f41f01e3018d39df38cc77432fd16f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.8,<4.0
    - std-uritemplate >=0.0.38,<2.0.0
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_abstractions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/abstractions
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-python/tree/main/packages/abstractions
  doc_url: https://github.com/microsoft/kiota-python/blob/main/packages/abstractions/README.md

extra:
  recipe-maintainers:
    - xylar
