{% set name = "microsoft-kiota-abstractions" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_abstractions-{{ version }}.tar.gz
  sha256: b34585f56a6023d38909edf7bfddeb9f3aa4b69727d138a6636f95eee3d1064b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core>=1.0.0
  run:
    - python >=3.8,<4.0
    - std-uritemplate >=0.0.38,<2.0.0
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_abstractions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/kiota-abstractions-python
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-abstractions-python
  doc_url: https://github.com/microsoft/kiota-abstractions-python/blob/main/README.md

extra:
  recipe-maintainers:
    - xylar
