{% set name = "microsoft-kiota-abstractions" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/microsoft_kiota_abstractions-{{ version }}.tar.gz
  sha256: 29cdafe8d0672f23099556e0b120dca6231c752cca9393e1e0092fa9ca594572

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }},<4.0
    - std-uritemplate >=2.0.0
    - opentelemetry-api >=1.27.0
    - opentelemetry-sdk >=1.27.0

test:
  imports:
    - kiota_abstractions
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/kiota-python/tree/main/packages/abstractions
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoft/kiota-python/tree/main/packages/abstractions
  doc_url: https://github.com/microsoft/kiota-python/blob/main/packages/abstractions/README.md

extra:
  recipe-maintainers:
    - xylar
